name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Initialize Job
        run: echo "Initializing Security Scan..."

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set EnvVar ShouldGitleaksRun
        run: echo "SHOULD_GITLEAKS_RUN=true" >> $GITHUB_ENV

      - name: Install GitLeaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.14.0/gitleaks_8.14.0_linux_x64.tar.gz | tar -xz -C /usr/local/bin gitleaks

      - name: GitLeaks Scan
        if: env.SHOULD_GITLEAKS_RUN == 'true'
        run: gitleaks detect --source . --no-banner

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Run Linter
        run: pnpm run lint

      - name: Run Security Analysis (ESLint Plugin Security)
        run: pnpm audit

      - name: Finalize Job
        run: echo "Security Scan Complete!"

  build_and_validation:
    name: Build & Validation
    runs-on: ubuntu-latest
    needs: security_scan

    steps:
      - name: Initialize Job
        run: echo "Initializing Build & Validation..."

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Run Linter
        run: pnpm run lint

      - name: Run Unit Tests
        run: pnpm run test

      - name: Publish Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results

      - name: Build Project
        run: pnpm run build

      - name: Finalize Job
        run: echo "Build & Validation Complete!"

  deploy_development:
    name: Deploy Development
    runs-on: ubuntu-latest
    needs: build_and_validation
    if: github.event_name == 'push'
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - name: Initialize Job
        run: echo "Initializing Deployment to Development..."

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm setup

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Vercel (Development)
        run: |
          pnpm install -g vercel
          vercel --prod --token $VERCEL_TOKEN --org-id $VERCEL_ORG_ID --project-id $VERCEL_PROJECT_ID --scope development

      - name: Finalize Job
        run: echo "Deployment to Development Complete!"

  deploy_production:
    name: Deploy Production
    runs-on: ubuntu-latest
    needs: build_and_validation
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - name: Initialize Job
        run: echo "Initializing Deployment to Production..."
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Vercel (Production)
        run: |
          pnpm install -g vercel
          vercel --prod --token $VERCEL_TOKEN --org-id $VERCEL_ORG_ID --project-id $VERCEL_PROJECT_ID --scope production

      - name: Finalize Job
        run: echo "Deployment to Production Complete!"
